config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'admin' => 'admin/reports#index'

  resources :countries, only: [:index, :show]
  resources :abroad_universities, only: :show
  resources :reports, only: :show

  namespace :admin do
    resources :reports
  end
end

app/models/abroad_university.rb
class AbroadUniversity < ApplicationRecord
  belongs_to :country
  has_many :reports
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  belongs_to :region
  has_many :abroad_universities
end

app/models/from_university.rb
class FromUniversity < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :countries
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :abroad_university
end

app/controllers/abroad_universities_controller.rb
class AbroadUniversitiesController < ApplicationController
  def show
    @abroad_univ = AbroadUniversity.find(params[:id])
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout 'admin'
  before_action :basic_auth

  def basic_auth
    authenticate_or_request_with_http_basic do |user,pass|
      user == ENV["BASIC_AUTH"] && pass = ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::AdminController
  before_action :set_report, only: [:show, :edit, :update]
  before_action :set_abroad_university, only: [:new, :edit]

  def index
    @reports = Report.all
  end

  def show
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(target_params)
    if @report.save
      redirect_to admin_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @report.update(target_params)
      redirect_to admin_path
    else
      render :edit
    end
  end

  def destroy
  end

  private
  def target_params
    params.require(:report).permit(
      :name,
      :abroad_university_id
    )
  end

  def set_report
    @report = Report.find(params[:id])
  end

  def set_abroad_university
    @abroad_universities = AbroadUniversity.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def index
    @regions = Region.all
  end

  def show
    @country = Country.find(params[:id])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def show
    @report = Report.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/abroad_universities/show.html.erb
<h1>
  <%= @abroad_univ.name %>
</h1>
<img src="https://i0.wp.com/wondertrip.jp/img/20160802/iStock_58925298_MEDIUM.jpg?w=730" style="width: 100%;">
<p>皆の声</p>
<ul>
  <% @abroad_univ.reports.each do |repo| %>
    <li>
      <%= link_to report_path(repo) do %>
        <%= repo.name %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/admin/reports/_form.html.slim
.container
  - if @report.errors.any?
    #error_explanation
      h3 = "#{ pluralize(@report.errors.count, "") }: 入力を確認してください。"
      ul
        - @report.errors.full_messages.each do |msg|
          li = msg
  = form_for ["admin", @report], html: { class: "form-horizontal" } do |f|
    .form-group
      label.col-sm-2.control-label for="InputEmail"  投稿者名
      .col-sm-10
        = f.text_field :name, class: "form-control", placeholder: "投稿者"
    .form-group
      label.col-sm-2.control-label for="InputEmail"  大学
      .col-sm-10
        = f.collection_select :abroad_university_id, @abroad_universities, :id, :name, {}, class: "form-control"
    .form-group
      .col-sm-offset-2.col-sm-10
        button.btn.btn-default type="submit" 更新

app/views/admin/reports/edit.html.slim
.container
  h1 「現地からの声」編集
  = render "form"

app/views/admin/reports/index.html.slim
.container
  p style="margin-top: 10px;"
    = link_to '「現地からの声」作成', new_admin_report_path, class: "btn btn-success"
  .panel.panel-info
    .panel-heading
      .panel-title 「現地からの声」一覧
    .panel-body
      br
      table.table.table-bordered.table-hover
        thead
          th.bg-primary 投稿者名
          th.bg-primary 大学
          th.bg-primary 操作
        tbody
          - @reports.each do |report|
            tr
              td = report.name
              td = report.abroad_university.name
              td
                = link_to "編集", edit_admin_report_path(report), class: "btn btn-success"
                = link_to "削除", edit_admin_report_path(report), class: "btn btn-danger", style: "margin-left: 8px;"

app/views/admin/reports/new.html.slim
.container
  h1 「現地からの声」新規作成
  = render "form"

app/views/countries/index.html.erb
<h1>留学先の国一覧ページ</h1>
<ul>
  <% @regions.each do |region| %>
    <li>
      <%= region.name %>
      <ul>
        <% region.countries.each do |country| %>
          <li>
            <%= link_to country.name, country_path(country) %>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/countries/show.html.erb
<h1>
  <%= @country.name %> の大学
</h1>
<ul>
  <% @country.abroad_universities.each do |univ| %>
    <li>
      <%= link_to abroad_university_path(univ) do %>
        <p><%= univ.name %></p>
        <br>
        <img src="https://i0.wp.com/wondertrip.jp/img/20160802/iStock_58925298_MEDIUM.jpg?w=730" style="width: 200px; height: 100px;">
        <p>
          ハーバード大学は、アメリカ合衆国の研究型私立大学であり、アイビー・リーグの一校。イギリス植民地時代の1636年に設置された、アメリカ最古の高等教育機関である。 ウィキペディア
        </p>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KoukanRyugaku</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'bootstrap.min.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "管理ページ", admin_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="navbarEexample">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">サイトへ戻る</a></li>
            <!-- <li><a href="#">メニューＢ</a></li>
            <li><a href="#">メニューＣ</a></li> -->
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KoukanRyugaku</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
        <div class="main-container">
            <main class="main">
                <%= yield %>

                <nav class="context-menu">
                    <ul>
                        <li>英語学習法</li>
                        <li>留学書類</li>
                        <li>面接</li>
                        <li>奨学金</li>
                        <li>就活</li>
                        <li>その他</li>
                    </ul>
                </nav>

            </main>

            <footer class="footer">
                Copyright &copy; 交換留学.com All rights reserved.
            </footer>
        </div>

        <header class="header">
            <div class="top-row">
                <span>LOGO</span>
                <span>koukanryugaku.com</span>
                <span>MENU</span>
            </div>
            <nav class="home-menu">
                <ul>
                    <li><%= link_to "Home", root_path %></li>
                    <li>動画ページ</li>
                    <li>ハウツー</li>
                    <li>留学先</li>
                    <li>お問い合わせ</li>
                </ul>
            </nav>
        </header>
    <style>
      html {
        --header-height: 140px;
        --context-menu-width: 200px;
      }

      .header {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: var(--header-height);
        background: #097ab9;
        color: white;
      }

      .header .home-menu ul li {
        float: left;
        padding: 1em;
      }

      .footer {
        height: 100px;
        background: #333;
        color: white;
      }

      .main-container {
        position: absolute;
        top: var(--header-height);
        right: 0;
        width: calc(100% - var(--context-menu-width));
        background: #eee;
      }

      .main-container .main {
        box-sizing: border-box;
        min-height: 100vh;
        padding: 1rem;
      }

      .main-container .context-menu {
        position: fixed;
        top: var(--header-height);
        left: 0;
        width: var(--context-menu-width);
        min-height: calc(100vh - var(--header-height));
        background: #00c0e2;
        color: white;
      }

    </style>
  </body>
</html>

app/views/reports/show.html.erb
<h1>
  <%= @report.name %>の声
</h1>
<p>
  この大学はとてもいい最高だ非常にいい。この大学はとてもいい最高だ非常にいい。この大学はとてもいい最高だ非常にいい。この大学はとてもいい最高だ非常にいい。この大学はとてもいい最高だ非常にいい。この大学はとてもいい最高だ非常にいい。この大学はとてもいい最高だ非常にいい。この大学はとてもいい最高だ非常にいい。この大学はとてもいい最高だ非常にいい。
</p>

app/views/top/index.html.erb
  <h1>トップページ</h1>
  <ul>
    <li>
      <%= link_to '動画一覧', '#' %>
    </li>
    <li>
      <%= link_to '教える内容', '#' %>
    </li>
    <li>
      <%= link_to '行ける所', countries_path %>
    </li>
  </ul>